swagger: '2.0'
info:
  title: Advisors API
  version: "0.0.1"

paths:
  /advisors:
    get:
      tags:
        - "advisors"
      description: "Get advisors for a student, either osu id or onid should be given."
      operationId: getAdvisors
      produces:
        - application/json
      parameters:
        - in: query
          name: osuID
          description: "OSU ID of a student"
          required: false
          type: integer
        - in: query
          name: onid
          description: "OSU onid of a student"
          required: false
          type: string
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: '#/definitions/ResultObjects'
        "404":
          description: "Resource not found"
          schema:
            $ref: "#/definitions/Errors"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Errors"

definitions:
  Attributes:
    properties:
      lastName:
        type: string
        description: Last name of the advisor.
      firstName:
        type: string
        description: First name of the advisor.
      termCodeEff:
        type: string
        description: The effective term code.
      advrCode:
        type: string
        description: Advisor type code.
      primIndicator:
        type: boolean
        description: Primary indicator

  Links:
    properties:
      self:
        type: string
      first:
        type: string
      last:
        type: string
      prev:
        type: string
      next:
        type: string

  ResultObjects:
    properties:
      links:
        $ref: "#/definitions/Links"
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"

  ResourceObject:
    properties:
      id:
        description: "Pidm for the advisor."
        type: string
      type:
        description: "Resource type: advisor"
        type: string
      attributes:
        $ref: "#/definitions/Attributes"

  Error:
    properties:
      status:
        type: integer
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.

  Errors:
    title: ArrayOfErrors
    type: array
    items:
      $ref: "#/definitions/Error"
